ДЗ1
Salex406/2020-1-Atom-QA-Python-A-Zharikov pull request #1
Opened 2020-03-03 21:01 UTC by Salex406

#Домашнее задание №1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
 1)Написано по 5 тестов на каждую из структур:

List
Set
Dictionary
String
Int 
Все тесты зелёные.

2) Код проверен с помощью pycodestyle

2020-03-05 21:24 UTC, sniiick requested changes
1. Куча ненужных *.pyc файлов в ревью из __pycache__. Явно не хватает .gitignore
2. Что то там в мастере произошло с созданием и удалением README.md и pull_request_template.md, надо либо поправить там, либо вернуть их обратно в этом ревью.

2020-03-05 21:24 UTC, snicks92 commented on h1/conftest.py
> +from fixtures.fixtures import *
Не хватает пустой строки в конце файла

2020-03-05 22:31 UTC, Salex406 commented
Исправил строки в conftest.py и fixtures.py
Добавил readme и pull_request_template в мастер
Настроил gitignore

2020-03-07 17:04 UTC, sniiick approved these changes

2020-03-07 17:04 UTC, merged