Qa python homework 3
Salex406/2020-1-Atom-QA-Python-A-Zharikov pull request #3
Opened 2020-05-01 19:52 UTC by Salex406

# Домашнее задание № 3
# Пояснения даны в файле *readme*
Прошу @snicks92 или @z1ll1 или @sk1995 проверить его.
# Что было сделано:

## Bash scripting
+ Написан скрипт на bash и python для анализа готового access.log

+ Есть возможность указать директорию где искать конкретный файл с логом.
+ Для access.log файла собирается следующая информация:

+ Общее количество запросов
+ Количество запросов по типу, например: GET - 20, POST - 10 и т.д. (0,5 балла)
+ Топ 10 самых больших по размеру запросов, должно быть видно url, код, число запросов (1 балл)
+ Топ 10 запросов по количеству, которые завершились клиентской ошибкой, должно быть видно url, статус код, ip адрес (1 балл)
+ Топ 10 запросов-редиректов по размеру запроса, должно быть видно url, статус код, ip адрес (1 балл)
+ Результаты сохраняются в файл(подробности в readme)

## Работа с БД, ORM

+ Создана mysql БД для логов, заполняется скриптом.
+ Написан коннектор к базе данных. Написан тест на создание сущности с использованием ORM.

## Работа с Flask, Mock

+ Написан собственный HTTP клиент с использованием библиотеки socket
+ Реализована функция, возвращающая в формате json: код ответа, заголовки, тело ответа

+ Написан собственный HTTP Mock сервер на flask.
+ реализован endpoint, который сохраняет в моке полученные данные для тестов в словарь
+ реализовано для тестов 2 endpoint'а, один для GET, другой для POST запросов
+ Написаны тесты, на собственный мок сервер с использованием собственного клиента
+ мок поднимается 1 раз, перед первым тестом, заввершается после выполнения последнего теста; все тестовые данные записываются 1 раз и + + потом используются для тестов

## Настройка Linux

+ поднят sshd демон на порту 2003 без выключения selinux и firewalld
+ поднят nginx демон порту 81 без выключения selinux и firewalld (1,5 балла)
+ Подключение к удаленной машине по ssh

+ Написаны тесты:

+ подключение к удаленной машине и получение прав root, проверка через whoami
+ подключение к удаленной машине, проверка что nginx запущен на порту отличном от дефолтного: через http и ssh
+ выполняем запрос к nginx, подключаемся к удаленной машине и проверяем что добавилась запись в access log 
+ подключение к удаленной машине, запретить подключаться по http к nginx через firewalld, убедиться что подключение не проходит, но nginx на машине поднят и работает

2020-05-10 23:56 UTC, sniiick requested changes
все хорошо, мелкие замечания

2020-05-10 23:56 UTC, snicks92 commented on README.md
>  # 2020-1-Atom-QA-Python-A-Zharikov
Кажется этот файлик надо перенести в папку с домашкой, чтобы не менялся общий README

2020-05-10 23:56 UTC, snicks92 commented on h3/linux/code/script_bash.txt
> +nOfPATCH=$(cat $1 | grep PATCH | awk ' END{print NR}')
можно сделать cat 1 раз и записать результат в переменную, затем все действия выполнять уже на результат. будет на 9 действий меньше

2020-05-10 23:56 UTC, snicks92 commented on pull_request_template.md
> +# Пояснения даны в readme
править темплейт тоже не хорошо

2020-05-13 12:44 UTC, Salex406 commented on README.md
>  # 2020-1-Atom-QA-Python-A-Zharikov
Сделал

2020-05-13 12:44 UTC, Salex406 commented on h3/linux/code/script_bash.txt
> +nOfPATCH=$(cat $1 | grep PATCH | awk ' END{print NR}')
Готово

2020-05-13 12:44 UTC, Salex406 commented on pull_request_template.md
> +# Пояснения даны в readme
Устранил

2020-05-13 12:48 UTC, Salex406 commented
Исправил замечания

2020-05-14 12:00 UTC, sniiick approved these changes

2020-05-14 12:02 UTC, snicks92 commented
Все отлично, насколько я вижу нет возмлжности вывода в формате json в python parser и не выводятся на экран тело и код ответа в socket client, поэтому 1 балл сниму. Итого 20.

2020-05-14 12:02 UTC, merged

2020-05-14 12:14 UTC, Salex406 commented
С баллами согласен, но разве надо было выводить именно на экран?  Функция get_ans() клиента возвращает все необходимое в формате json и можно вывести при желании. Но печатать каждый раз все ответы выглядит странным )

2020-05-14 12:25 UTC, snicks92 commented
> С баллами согласен, но разве надо было выводить именно на экран? Функция get_ans() клиента возвращает все необходимое в формате json и можно вывести при желании. Но печатать каждый раз все ответы выглядит странным )

Если верить домашнему заданию:
```